name: Modify Config Files

on:
  schedule:
    - cron: "11 */6 * * *"   # هر 6 ساعت و 15 دقیقه
  workflow_dispatch:

jobs:
  modify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add prefix to protocol files
        run: |
          # VLESS
          if [ -f "splitted-by-protocol/vless.txt" ]; then
            sed -i '1s/^/Vless | https:\/\/t.me\/MerlinMax\n/' splitted-by-protocol/vless.txt
          fi

          # VMESS
          if [ -f "splitted-by-protocol/vmess.txt" ]; then
            sed -i '1s/^/Vmess | https:\/\/t.me\/MerlinMax\n/' splitted-by-protocol/vmess.txt
          fi

          # Trojan
          if [ -f "splitted-by-protocol/trojan.txt" ]; then
            sed -i '1s/^/Trojan | https:\/\/t.me\/MerlinMax\n/' splitted-by-protocol/trojan.txt
          fi

          # Shadowsocks
          if [ -f "splitted-by-protocol/shadowsocks.txt" ]; then
            sed -i '1s/^/Shadowsocks | https:\/\/t.me\/MerlinMax\n/' splitted-by-protocol/shadowsocks.txt
          fi

      - name: Commit changes
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto modify protocol files" || echo "No changes"
          git push
